#!/usr/bin/env bash
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/trusty64"
  
  config.vm.hostname = "seeder.dbs.local"
  config.vm.network :forwarded_port, guest: 3306, host: 3306, auto_correct: true
  config.vm.network "private_network", ip: "192.168.33.200"
  config.ssh.forward_agent = true
  
  config.vm.synced_folder "./", "/home/vagrant/tracker"
  
  config.vm.provider :virtualbox do |v|
    v.customize ["modifyvm", :id, "--memory", 2048]
  end

  config.vm.provision "shell", path: "script.sh"
end
